// react-grid/src/components/Grid.js
import React, { Component } from 'react';
import './Grid.scss';

export class Grid extends Component {
    render() {
        return (
            <div className="grid-builder">
                <table>
                    <thead>
                        <tr>
                            {this.createHeaderCells()}
                        </tr>
                    </thead>
                    <tbody>
                        { this.createRows() }
                    </tbody>
                </table >
            </div >
        );
    }

    createHeaderCells = () => {
        let headerCells = [];
        for (let i = 1; i <= this.props.columns; i++){
            headerCells.push(<th key={i}>Header {i}</th>)
        }
        return headerCells;
    }

    createOptionsForSelect = (i) => {
        let opts = [];
        for (let i = 1; i <= this.props.columns; i++){
            opts.push(<option key={i} value={i}>Option {i}</option>)
        }
        return opts;
    }

    createRowCellContent = (row, col) => {
        if (col % 3 == 0){
            return `${row}/${col}`;
        }
        if (col % 3 == 1){
            return <input type="text" value={row}></input>;
        }
        if (col % 3 == 2){
            return <select value={row}>{this.createOptionsForSelect(col)}</select>;
        }
    }
    
    createRowCells = (row) => {
        let rowCells = [];
        for (let i = 1; i <= this.props.columns; i++){
            rowCells.push(<td key={i}>{this.createRowCellContent(row, i)}</td>)
        }
        return rowCells;
    }

    createRows = () => {
        let rows = [];
        console.log(this.props);
        for (let i = 1; i <= this.props.rows; i++){
            rows.push(<tr key={i}>{this.createRowCells(i)}</tr>)
        }
        return rows;
    }

}

export default Grid;

// ng-grid/src/app/components/grid/grid.component.ts
import { Component, OnChanges, Input } from '@angular/core';

@Component({
  selector: 'app-grid',
  templateUrl: './grid.component.html',
  styleUrls: ['./grid.component.scss']
})
export class GridComponent implements OnChanges {

  @Input() columns: number = 5;
  @Input() rows: number = 20;
  arrCols: number[] = [];
  arrRows: number[] = [];

  constructor() { }

  ngOnChanges() {
    this.arrCols = Array(this.columns).fill(0);
    this.arrRows = Array(this.rows).fill(0);
  }

}

<table>
  <thead>
      <tr>
          <th *ngFor="let col of arrCols; let i = index">Header {{ i+1 }}</th>
      </tr>
  </thead>
  <tbody>
      <tr *ngFor="let row of arrRows; let r = index">
          <td *ngFor="let col of arrCols; let i = index">
              <ng-container *ngIf="i % 3 == 2">
                  {{ row }} / {{ col }}
              </ng-container>
              <ng-container *ngIf="i % 3 == 0">
                  <input type="text" [value]="r+1"/>
              </ng-container>
              <ng-container *ngIf="i % 3 == 1">
                  <select [value]="r+1">
                      <option *ngFor="let col of arrCols; let j = index" [value]="j">Option {{j+1}}</option>
                  </select>
              </ng-container>
          </td>
      </tr>
  </tbody>
</table>
