// react-grid/src/views/Forms.js
import React, { Component } from 'react';
import './Forms.scss';

export class Forms extends Component {

    constructor(){
        super();
        this.state = {
            count: 100
        }
    }

    render() {
        return (
            <div id="forms">
                <h1>This is a forms page</h1>
                <form className="forms-wrapper">
                    {this.createInputs()}
                    <button type="submit">Submit</button>
                </form>
            </div>
        );
    }

    generateSelectOptons = () => {
        let opts = [];
        opts.push(<option hidden value="">Placeholder</option>);
        for ( let i = 1; i <= this.state.count; i++){
            opts.push(<option value={i}>Value {i}</option>);
        }
        return opts;
    }

    createInputs = () => {
        let inputs = [];
        for ( let i = 1; i <= this.state.count; i++ ){
            inputs.push(
                <React.Fragment>
                    <input type="text" placeholder={'Input '+i} readOnly/>
                    <select readOnly>{this.generateSelectOptons()}</select>
                </React.Fragment>
            );
        }
        return inputs;
    }
}

export default Forms;

// ng-grid/src/app/views/forms/forms.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-forms',
  templateUrl: './forms.component.html',
  styleUrls: ['./forms.component.scss']
})
export class FormsComponent implements OnInit {

  count: number[];
  dropdownValues: string[] = Array.from(Array(this.count)).map((v,i)=>`Value ${i+1}`);

  constructor() { }

  ngOnInit() {
    this.count = Array(100).fill(0);
  }

}

<div class="forms">
  <h1>This is a forms page</h1>
  <form class="forms-wrapper">
    <ng-container *ngFor="let zero of count; let i = index">
      <input type="text" [placeholder]="'Input '+(i+1)">
      <select>
        <option hidden [value]="">Placeholder</option>
        <option *ngFor="let val of dropdownValues" [value]="val">{{val}}</option>
      </select>
    </ng-container>
    <button type="submit">Submit</button>
  </form>
</div>
