// vue-grid/src/components/Grid.vue
<template>
  <div class="grid-builder">
    <table>
        <thead>
            <tr>
                <th v-for="col in columns">Header {{ col }}</th>
            </tr>
        </thead>
        <tbody>
            <tr v-for="row in rows">
                <td v-for="col in columns">
                    <template v-if="col % 3 == 0">
                        {{ row }} / {{ col }}
                    </template>
                    <template v-if="col % 3 == 1">
                        <input type="text" :value="row"/>
                    </template>
                    <template v-if="col % 3 == 2">
                        <select :value="row">
                            <option v-for="i in columns" :value="i">Option {{i}}</option>
                        </select>
                    </template>
                </td>
            </tr>
        </tbody>
    </table>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

@Component
export default class Grid extends Vue {

  @Prop({default: 5}) columns!: number;
  @Prop({default: 20}) rows!: number;

}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped lang="scss">
@import 'styles/common';
.grid{
    width: 100%;
    height: 100%;
}
table{
    border-collapse: collapse;
    background: white;
    overflow: auto;
    height: calc(100% - 150px);
    width: 100%;
    table-layout: fixed;

    th, td{
        padding: 10px;
        border: 1px solid $border-color;
        transition: all 0.1s linear;
        font-size: 12px;
    }
    th{
        background-color: #e9e9e9;
        border-color: #d7d7d7;
        padding: 20px 10px;
    }
}
</style>

// react-grid/src/components/Grid.js
import React, { Component } from 'react';
import './Grid.scss';

export class Grid extends Component {
    render() {
        return (
            <div className="grid-builder">
                <table>
                    <thead>
                        <tr>
                            {this.createHeaderCells()}
                        </tr>
                    </thead>
                    <tbody>
                        { this.createRows() }
                    </tbody>
                </table >
            </div >
        );
    }

    createHeaderCells = () => {
        let headerCells = [];
        for (let i = 1; i <= this.props.columns; i++){
            headerCells.push(<th key={i}>Header {i}</th>)
        }
        return headerCells;
    }

    createOptionsForSelect = (i) => {
        let opts = [];
        for (let i = 1; i <= this.props.columns; i++){
            opts.push(<option key={i} value={i}>Option {i}</option>)
        }
        return opts;
    }

    createRowCellContent = (row, col) => {
        if (col % 3 == 0){
            return `${row}/${col}`;
        }
        if (col % 3 == 1){
            return <input type="text" value={row}></input>;
        }
        if (col % 3 == 2){
            return <select value={row}>{this.createOptionsForSelect(col)}</select>;
        }
    }
    
    createRowCells = (row) => {
        let rowCells = [];
        for (let i = 1; i <= this.props.columns; i++){
            rowCells.push(<td key={i}>{this.createRowCellContent(row, i)}</td>)
        }
        return rowCells;
    }

    createRows = () => {
        let rows = [];
        console.log(this.props);
        for (let i = 1; i <= this.props.rows; i++){
            rows.push(<tr key={i}>{this.createRowCells(i)}</tr>)
        }
        return rows;
    }

}

export default Grid;
